nrz_i = 'Sinal muda para representar um bit 1 e permanece o mesmo para representar um bit 0'
nrz_l = 'O nivel da voltagem representa o valor do bit'
ami = 'Bit 0 é representado por 0, enquanto um bit 1 é representado por um nível de tensão positivo ou negativo alternado'
pseudoternario = 'Bit 1 é representado por 0, enquanto um bit 0 é representado por um nível de tensão positivo ou negativo alternado'
manchester = 'Duracao de um bit é dividida pela metade, na primeira metade o bit permanece em um nivel, depois desloca-se'
manchester_diferencial = 'Existe sempre uma transição no meio do elemento, mas o valor é determinado no início'
mlt3 = 'Utiliza 3 niveis de sinais e reduz ao maximo o numero de zeros consecutivos'
differential_binary = 'Cada bit é codificado como a diferença entre o nível de sinal atual e o nível de sinal anterior'
